name: Android Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: Joshela/buildozer-action@master
        with:
          command: buildozer android release
          buildozer_version: master
